# Site settings
title: "Brandon Helwig"
name: "Brandon Helwig"
description: "Mountain biker, Gamer, Technologist."
url: "https://www.brandonhelwig.com"
email: web@brandonhelwig.com
public_key_url: "https://keybase.io/brhelwig"

github_username:  brhelwig
twitter_username: brhelwig
linkedin_username: brhelwig
instagram_username:  brhelwig
garmin_username: brhelwig
stack_of_username: 180881

resume_url: "/resume"
#blog_url: "/blog"

avatar: yes
avatar_img_path: "/assets/img/avatar2019.jpg"
avatar_alt_text: "Portrait of Brandon Helwig"

front_img: yes
front_img_path: "/assets/img/moab.jpg"
front_img_alt_text: "Photo of Mountain Bike Handlebars overlooking a red rocky cliff in Moab, Utah."

favicon_img: yes
favicon_img_path: "/assets/img/favicon.png"

markdown: kramdown
permalink: pretty
